import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { it } from "node:test";
import { createServer } from "./index.js";
import { createNativeProjectRoot } from "./semantic/project-root/project-root.js";
import { assertFileFallback, adapterWithSymbols, symbol, unavailableAdapter } from "./testing/index-test-server-support.js";

it("uses the production search boundary to filter generated files and report invalid classification configuration", async () => {
  const root = mkdtempSync(join(tmpdir(), "code-explorer-server-discovery-"));
  try {
    mkdirSync(join(root, "src"));
    mkdirSync(join(root, "generated"));
    writeFileSync(join(root, "src", "Helper.ts"), "export const helper = 1;\n");
    writeFileSync(join(root, "generated", "Helper.ts"), "// <auto-generated>\nexport const helper = 1;\n");
    writeFileSync(join(root, ".code-explorer.json"), "{ invalid");
    const server = createServer({ projectRoot: createNativeProjectRoot(root) });
    const search = await server.call("code_search", { query: "helper" });
    const status = await server.call("code_status", { action: "status" });
    assert.equal("code" in search, false);
    assert.equal("code" in status, false);
    if ("code" in search || "code" in status) throw new Error("expected discovery response");
    assert.deepEqual((search.data.candidates as { path: string }[]).map((candidate) => candidate.path), ["src/Helper.ts"]);
    assert.equal(status.data.classification_config_invalid, true);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("keeps file discovery available when a semantic backend is unavailable", async () => {
  const root = mkdtempSync(join(tmpdir(), "code-explorer-server-file-fallback-"));
  try {
    mkdirSync(join(root, "src"));
    writeFileSync(join(root, "src", "client.ts"), "export const client = true;\n");
    const server = createServer({ projectRoot: createNativeProjectRoot(root), adapters: [unavailableAdapter()] });
    await assertFileFallback(server);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("returns native workspace symbols through code_search after classification and filters", async () => {
  const root = mkdtempSync(join(tmpdir(), "code-explorer-server-symbols-"));
  try {
    mkdirSync(join(root, "src"));
    mkdirSync(join(root, "tests"));
    mkdirSync(join(root, "generated"));
    writeFileSync(join(root, "src", "main.rs"), "fn helper() {}\n");
    writeFileSync(join(root, "tests", "helper_test.rs"), "fn helper() {}\n");
    writeFileSync(join(root, "generated", "helper.rs"), "// <auto-generated>\nfn helper() {}\n");
    const adapter = adapterWithSymbols([symbol("function", "src/main.rs"), symbol("class", "src/main.rs"), symbol("function", "tests/helper_test.rs"), symbol("function", "generated/helper.rs")]);
    const server = createServer({ projectRoot: createNativeProjectRoot(root), adapters: [adapter] });
    const result = await server.call("code_search", { query: "helper", kinds: ["function"], path_globs: ["src/**"], limit: 1 });
    assert.equal("code" in result, false);
    if ("code" in result) throw new Error("expected discovery response");
    assert.deepEqual((result.data.candidates as { identity: string }[]).map((candidate) => candidate.identity), ["function:src/main.rs"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
