import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { it } from "node:test";
import { createDiscoveryPipeline } from "../../../discovery/pipeline.js";
import { createNativeProjectRoot } from "../../../semantic/api/public-api.js";
import { writeWorkspaceFiles } from "./workspace-files-fixture.js";

it("filters classified files before matcher ranking and the " + "limit", () => {
  const root = mkdtempSync(join(tmpdir(), "code-explorer-discovery-"));
  try {
    writeWorkspaceFiles(root, {
      "src/Helper.ts": "export const helper = 1;\n",
      "tests/Helper.test.ts": "export const helper = 1;\n",
      "generated/Helper.ts": "// <auto-generated>\nexport const helper = 1;\n",
    });
    const pipeline = createDiscoveryPipeline(createNativeProjectRoot(root));
    assert.deepEqual(
      pipeline.search("helper", { limit: 1 }).map((item) => item.path),
      ["src/Helper.ts"],
    );
    assert.deepEqual(
      pipeline.search("helper", { content: "tests" }).map((item) => item.path),
      ["tests/Helper.test.ts"],
    );
    assert.deepEqual(
      pipeline
        .search("helper", { include_generated: true })
        .map((item) => item.path),
      ["generated/Helper.ts", "src/Helper.ts", "tests/Helper.test.ts"],
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
