import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { it } from "node:test";
import { createDiscoveryPipeline } from "../../../discovery/pipeline.js";
import { createNativeProjectRoot } from "../../../semantic/api/public-api.js";
import { symbol } from "./symbol-fixture.js";
import { writeWorkspaceFiles } from "./workspace-files-fixture.js";

it(
  "filters native workspace-symbol candidates before " + "ranking and limiting",
  () => {
    const root = mkdtempSync(
      join(tmpdir(), "code-explorer-discovery-symbols-"),
    );
    try {
      writeWorkspaceFiles(root, {
        "src/main.rs": "fn helper() {}\n",
        "tests/helper_test.rs": "fn helper() {}\n",
        "generated/helper.rs": "// <auto-generated>\nfn helper() {}\n",
      });
      const pipeline = createDiscoveryPipeline(createNativeProjectRoot(root));
      const symbols = [
        symbol("function", "src/main.rs"),
        symbol("class", "src/main.rs"),
        symbol("function", "tests/helper_test.rs"),
        symbol("function", "generated/helper.rs"),
      ];
      assert.deepEqual(
        pipeline
          .search(
            "helper",
            { kinds: ["function"], path_globs: ["src/**"], limit: 1 },
            symbols,
          )
          .map((item) => item.identity),
        ["function:src/main.rs"],
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  },
);
