export const syntheticStoreEntries = {
  "alpha/first.md": [
    "---",
    "key: alpha.first",
    "title: First synthetic entry",
    "chapter: alpha",
    "section: alpha.topic",
    "summary: Shared synthetic summary",
    "sources:",
    "  - label: synthetic fixture",
    "    project: fixture-project",
    "    language: TypeScript",
    "related_keys:",
    "  - alpha.second",
    "project: fixture-project",
    "language: TypeScript",
    "---",
    "Shared synthetic content for the first entry.",
  ].join("\n"),
  "alpha/second.md": [
    "---",
    "key: alpha.second",
    "title: Second synthetic entry",
    "chapter: alpha",
    "section: alpha.topic",
    "summary: Shared synthetic summary",
    "sources:",
    "  - label: synthetic fixture",
    "---",
    "Shared synthetic content for the second entry.",
  ].join("\n"),
  "beta/third.md": [
    "---",
    "key: beta.third",
    "title: Third synthetic entry",
    "chapter: beta",
    "section: beta.topic",
    "summary: Separate synthetic summary",
    "sources:",
    "  - label: synthetic fixture",
    "---",
    "Separate synthetic content.",
  ].join("\n"),
};

export const syntheticToolEntries = {
  "synthetic/first.md": [
    "---",
    "key: synthetic.first",
    "title: First synthetic entry",
    "chapter: synthetic",
    "section: synthetic.topic",
    "summary: Synthetic summary",
    "sources:",
    "  - label: fixture",
    "related_keys:",
    "  - synthetic.second",
    "---",
    "Synthetic full content.",
  ].join("\n"),
  "synthetic/second.md": [
    "---",
    "key: synthetic.second",
    "title: Second synthetic entry",
    "chapter: synthetic",
    "section: synthetic.topic",
    "summary: Related synthetic summary",
    "sources:",
    "  - label: fixture",
    "---",
    "Related full content.",
  ].join("\n"),
};
