export const LANG_BY_EXT = {
  ".ts": "ts",
  ".tsx": "ts",
  ".mts": "ts",
  ".cts": "ts",
  ".js": "ts",
  ".jsx": "ts",
  ".mjs": "ts",
  ".cjs": "ts",
  ".cs": "cs",
  ".rs": "rs",
  ".py": "py",
  ".go": "go",
  ".c": "cpp",
  ".java": "java",
  ".kt": "java",
  ".cpp": "cpp",
  ".cc": "cpp",
  ".hpp": "cpp",
  ".h": "cpp",
};

export const DEFAULT_THRESHOLDS = {
  "line-length": { medium: 80, high: 120 },
  "file-length": { medium: 100, high: 300 },
  "function-length": { medium: 30, high: 60 },
  complexity: { medium: 5, high: 10 },
  "param-count": { medium: 3, high: 7 },
  "nesting-depth": { medium: 3, high: 5 },
  "types-per-file": { medium: null, high: 1 },
  "duplicate-block": { medium: 1, high: 2 },
  "comment-bloat": { medium: 2, high: 4 },
};

export const PRESENCE_SEVERITY = {
  "else-branch": "medium",
  "unnamed-tuple": "high",
  "dead-export": "high",
  "unused-local": "high",
  "test-only-export": "medium",
  "commented-out-code": "high",
  "comment-restates-code": "medium",
  "comment-metadata": "medium",
  "comment-placeholder": "medium",
  "comment-missing-reference": "medium",
  "output-parameter": "medium",
  "flag-parameter": "medium",
  "wildcard-import": "medium",
  "naming-encoding": "medium",
  "build-entrypoint": "medium",
  "test-entrypoint": "medium",
  "todo-marker": "medium",
  "stateless-method": "medium",
};

export const DUPLICATE_WINDOW = 6;
