import type { BurstReport } from "./types.js";

export const VERBOSE_BURST_FIXTURE: BurstReport = {
  id: "verbose-burst",
  startTimestampMs: Date.UTC(2025, 0, 1),
  endTimestampMs: Date.UTC(2025, 0, 2),
  commitCount: 2,
  fileCount: 2,
  survivors: [],
  findings: [
    {
      classification: "advisory",
      burstId: "verbose-burst",
      path: "src/unavailable.ts",
      activity: {
        identity: "src/unavailable.ts",
        path: "src/unavailable.ts",
        createdInBurst: true,
        burstCommits: 3,
        postBurstCommits: 0,
        existsAtHead: true,
      },
      score: 0.9,
      scoreBasis: "git-only",
      subscores: { churn: 1, abandonment: 1 },
      referenceAvailability: "unavailable",
      strongInboundReferences: 0,
      candidateNeighbors: [],
      liveNeighbors: [],
    },
    {
      classification: "advisory",
      burstId: "verbose-burst",
      path: "src/complete.ts",
      activity: {
        identity: "src/complete.ts",
        path: "src/complete.ts",
        createdInBurst: false,
        burstCommits: 2,
        postBurstCommits: 4,
        existsAtHead: true,
      },
      score: 0.8,
      scoreBasis: "full",
      subscores: {
        churn: 0.5,
        abandonment: 0,
        referenceWeakness: 0.5,
        clusterIsolation: 0.5,
      },
      referenceAvailability: "complete",
      strongInboundReferences: 1,
      candidateNeighbors: ["./src/candidate.ts"],
      liveNeighbors: ["src\\live.ts"],
    },
  ],
  deletedPaths: [],
};
