import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
export function writePracticeFiles(root: string) {
  for (const directory of ["src", "generated", "tests", ".git"])
    mkdirSync(join(root, directory));
  writeFileSync(
    join(root, "src", "PaymentService.rs"),
    "fn payment_service() {}\n",
  );
  writeFileSync(join(root, "src", "WindowsPath.rs"), "fn windows_path() {}\n");
  writeFileSync(join(root, "src", "Alpha.rs"), "fn alpha() {}\n");
  writeFileSync(join(root, "src", "Beta.rs"), "fn beta() {}\n");
  writeFileSync(join(root, "src", "Gamma.rs"), "fn gamma() {}\n");
  writeFileSync(
    join(root, "generated", "PaymentService.rs"),
    "// <auto-generated>\nfn payment_service() {}\n",
  );
  writeFileSync(
    join(root, "tests", "payment_service_test.rs"),
    "fn payment_service_test() {}\n",
  );
  writeFileSync(join(root, ".env"), "secret=value\n");
  writeFileSync(join(root, ".git", "config"), "[core]\n");
}
