import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { it } from "node:test";
import { createNativeProjectRoot } from "../semantic/project-root.js";
import { createDiscoveryPipeline } from "./pipeline.js";

it("filters classified files before matcher ranking and the limit", () => {
  const root = mkdtempSync(join(tmpdir(), "code-explorer-discovery-"));
  try {
    mkdirSync(join(root, "src"));
    mkdirSync(join(root, "tests"));
    mkdirSync(join(root, "generated"));
    writeFileSync(join(root, "src", "Helper.ts"), "export const helper = 1;\n");
    writeFileSync(join(root, "tests", "Helper.test.ts"), "export const helper = 1;\n");
    writeFileSync(join(root, "generated", "Helper.ts"), "// <auto-generated>\nexport const helper = 1;\n");
    const pipeline = createDiscoveryPipeline(createNativeProjectRoot(root));
    assert.deepEqual(
      pipeline.search("helper", { limit: 1 }).map((item) => item.path),
      ["src/Helper.ts"],
    );
    assert.deepEqual(
      pipeline.search("helper", { content: "tests" }).map((item) => item.path),
      ["tests/Helper.test.ts"],
    );
    assert.deepEqual(
      pipeline.search("helper", { include_generated: true }).map((item) => item.path),
      ["generated/Helper.ts", "src/Helper.ts", "tests/Helper.test.ts"],
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("keeps defaults usable while surfacing an invalid classification configuration", () => {
  const root = mkdtempSync(join(tmpdir(), "code-explorer-discovery-invalid-"));
  try {
    mkdirSync(join(root, "src"));
    writeFileSync(join(root, "src", "Helper.ts"), "export const helper = 1;\n");
    writeFileSync(join(root, ".code-explorer.json"), "{ invalid");
    const pipeline = createDiscoveryPipeline(createNativeProjectRoot(root));
    assert.deepEqual(pipeline.status(), { classification_config_invalid: true });
    assert.deepEqual(
      pipeline.search("helper", {}).map((item) => item.path),
      ["src/Helper.ts"],
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("filters native workspace-symbol candidates before ranking and limiting", () => {
  const root = mkdtempSync(join(tmpdir(), "code-explorer-discovery-symbols-"));
  try {
    mkdirSync(join(root, "src"));
    mkdirSync(join(root, "tests"));
    mkdirSync(join(root, "generated"));
    writeFileSync(join(root, "src", "main.rs"), "fn helper() {}\n");
    writeFileSync(join(root, "tests", "helper_test.rs"), "fn helper() {}\n");
    writeFileSync(join(root, "generated", "helper.rs"), "// <auto-generated>\nfn helper() {}\n");
    const pipeline = createDiscoveryPipeline(createNativeProjectRoot(root));
    const symbols = [
      symbol("function", "src/main.rs"),
      symbol("class", "src/main.rs"),
      symbol("function", "tests/helper_test.rs"),
      symbol("function", "generated/helper.rs"),
    ];
    assert.deepEqual(
      pipeline
        .search("helper", { kinds: ["function"], path_globs: ["src/**"], limit: 1 }, symbols)
        .map((item) => item.identity),
      ["function:src/main.rs"],
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

function symbol(kind: string, path: string) {
  return {
    id: `${kind}:${path}`,
    name: "helper",
    language: "rust" as const,
    kind,
    location: { path, range: { start: { line: 0, character: 0 }, end: { line: 0, character: 6 } } },
  };
}
