import { lstatSync, readdirSync } from "node:fs";
import { join } from "node:path";
import type { SymbolIdentity } from "../semantic/contract.js";
import type { ProjectRoot } from "../semantic/project-root.js";
import {
  type ClassificationConfigStatus,
  classifyProjectPath,
  loadClassificationConfig,
  matchesDiscoveryFilters,
  type PathClassification,
} from "./classification.js";
import { isClassificationConfigPath } from "./config-path.js";
import { type DiscoveryMatch, matchDiscoveryCandidates } from "./matcher.js";
import { isSensitiveProjectPath } from "./sensitive-paths.js";

export type DiscoveryResult = DiscoveryMatch & PathClassification;
export type DiscoveryPipeline = {
  search(query: string, filters: DiscoveryFilters, symbols?: readonly SymbolIdentity[]): DiscoveryResult[];
  status(): ClassificationConfigStatus;
};
export type DiscoveryFilters = {
  path_globs?: readonly string[];
  languages?: readonly string[];
  kinds?: readonly string[];
  content?: "all" | "production" | "tests";
  include_generated?: boolean;
  limit?: number;
};

/** Loads classification once for this project generation and filters before matching or limiting. */
export function createDiscoveryPipeline(root: ProjectRoot): DiscoveryPipeline {
  const loaded = loadClassificationConfig(root.canonicalPath);
  const candidates = collectSourceFiles(root).map((path) => ({
    type: "file" as const,
    path,
    identity: `file:${path}`,
    classification: classifyProjectPath(path, loaded.config, hasGeneratedHeader(root, path)),
  }));
  return {
    status: () => loaded.status,
    search(query, filters, symbols = []) {
      // Adapter locations are untrusted. Reject denied paths before classification can read a header.
      const allowedSymbols = symbols.filter((symbol) => !isSensitiveProjectPath(symbol.location.path));
      const semanticCandidates = allowedSymbols.map((symbol) => ({
        type: "symbol" as const,
        name: symbol.name,
        path: symbol.location.path,
        kind: symbol.kind,
        identity: symbol.id,
        classification: classifyProjectPath(
          symbol.location.path,
          loaded.config,
          hasGeneratedHeader(root, symbol.location.path),
        ),
      }));
      const allCandidates = [...candidates, ...semanticCandidates];
      const classifications = new Map(allCandidates.map((candidate) => [candidate.identity, candidate.classification]));
      const allowed = allCandidates.filter((candidate) => {
        return matchesDiscoveryFilters(candidate.path, candidate.classification, filters, {
          language:
            candidate.type === "symbol"
              ? allowedSymbols.find((symbol) => symbol.id === candidate.identity)?.language
              : languageForPath(candidate.path),
          ...(candidate.type === "symbol" ? { kind: candidate.kind } : {}),
        });
      });
      return matchDiscoveryCandidates(query, allowed)
        .map((candidate) => {
          const classification = classifications.get(candidate.identity);
          if (!classification) throw new Error("missing discovery classification");
          return { ...candidate, ...classification };
        })
        .slice(0, Math.max(0, filters.limit ?? 50));
    },
  };
}

function hasGeneratedHeader(root: ProjectRoot, path: string): boolean {
  try {
    const header = root.protectedRead(path).bytes.slice(0, 2048);
    return /(?:^|\n)\s*(?:\/\/|#|\/\*)\s*(?:<auto-generated>|auto-generated\b|generated by\b)/iu.test(header);
  } catch {
    return false;
  }
}

function collectSourceFiles(root: ProjectRoot): string[] {
  const found: string[] = [];
  const visit = (directory: string, prefix: string) => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
      const absolute = join(directory, entry.name);
      if (
        isSensitiveProjectPath(relative) ||
        isClassificationConfigPath(relative) ||
        lstatSync(absolute).isSymbolicLink()
      )
        continue;
      if (entry.isDirectory()) {
        if (!isIgnoredDirectory(relative)) visit(absolute, relative);
      } else if (entry.isFile() && languageForPath(relative)) found.push(relative);
    }
  };
  visit(root.canonicalPath, "");
  return found;
}

function isIgnoredDirectory(path: string): boolean {
  return path.split("/").some((part) => /^(node_modules|\.git|\.hg|\.svn|\.venv|venv)$/iu.test(part));
}

function languageForPath(path: string): string | undefined {
  const extension = path.split(".").at(-1)?.toLowerCase();
  return (
    {
      rs: "rust",
      py: "python",
      pyi: "python",
      cs: "csharp",
      ts: "typescript",
      tsx: "typescript",
      js: "javascript",
      jsx: "javascript",
    } as Record<string, string>
  )[extension ?? ""];
}
