import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { it } from "node:test";
import type { SymbolIdentity } from "../semantic/contract.js";
import { createNativeProjectRoot } from "../semantic/project-root.js";
import { createDiscoveryPipeline } from "./pipeline.js";

it("runs the bounded discovery practice fixture", () => {
  const root = mkdtempSync(join(tmpdir(), "code-explorer-discovery-practice-"));
  try {
    for (const directory of ["src", "generated", "tests", ".git"]) mkdirSync(join(root, directory));
    writeFileSync(join(root, "src", "PaymentService.rs"), "fn payment_service() {}\n");
    writeFileSync(join(root, "src", "WindowsPath.rs"), "fn windows_path() {}\n");
    writeFileSync(join(root, "src", "Alpha.rs"), "fn alpha() {}\n");
    writeFileSync(join(root, "src", "Beta.rs"), "fn beta() {}\n");
    writeFileSync(join(root, "src", "Gamma.rs"), "fn gamma() {}\n");
    writeFileSync(join(root, "generated", "PaymentService.rs"), "// <auto-generated>\nfn payment_service() {}\n");
    writeFileSync(join(root, "tests", "payment_service_test.rs"), "fn payment_service_test() {}\n");
    writeFileSync(join(root, ".env"), "secret=value\n");
    writeFileSync(join(root, ".git", "config"), "[core]\n");

    const pipeline = createDiscoveryPipeline(createNativeProjectRoot(root));
    const symbols = [
      symbol("payment_service", "src/PaymentService.rs", "production"),
      symbol("payment_service", "generated/PaymentService.rs", "generated"),
      symbol("windows_path", "src\\WindowsPath.rs", "windows"),
    ];

    const misspelling = pipeline.search("paymnt_service", {}, symbols);
    assert.ok(misspelling.some(({ identity, match_class }) => identity === "production" && match_class === "fuzzy"));

    const defaultDuplicates = pipeline.search("payment_service", {}, symbols);
    assert.equal(
      defaultDuplicates.some(({ identity }) => identity === "generated"),
      false,
    );
    const generatedDuplicates = pipeline.search("payment_service", { include_generated: true }, symbols);
    assert.equal(
      generatedDuplicates.some(({ identity }) => identity === "generated"),
      true,
    );

    assert.deepEqual(
      pipeline.search("payment_service", { content: "tests" }, symbols).map(({ path, content }) => [path, content]),
      [["tests/payment_service_test.rs", "test"]],
    );

    const visible = pipeline.search("payment_service", { include_generated: true }, symbols);
    assert.equal(
      visible.some(({ path }) => /\.env|\.git\//u.test(path)),
      false,
    );

    const bounded = pipeline.searchResult("payment_service", { include_generated: true, limit: 2 }, symbols);
    assert.equal(bounded.candidates.length, 2);
    assert.ok(bounded.omitted_candidate_count > 0);
    assert.deepEqual(bounded.available_narrowing_filters, [
      "path_globs",
      "languages",
      "kinds",
      "content",
      "include_generated",
    ]);

    assert.ok(pipeline.search("windows_path", {}, symbols).every(({ path }) => path === "src/WindowsPath.rs"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

function symbol(name: string, path: string, id: string): SymbolIdentity {
  return {
    id,
    name,
    language: "rust",
    kind: "function",
    location: { path, range: { start: { line: 0, character: 0 }, end: { line: 0, character: name.length } } },
  };
}
