import { lstatSync, readdirSync } from "node:fs";
import { join } from "node:path";
import type { ProjectRoot } from "../semantic/api/public-api.js";
import { isClassificationConfigPath } from "./config-path.js";
import { isSensitiveProjectPath } from "./sensitive-paths.js";

export function collectSourceFiles(root: ProjectRoot): string[] {
  const found: string[] = [];
  visit(root.canonicalPath, "", found);
  return found;
}

function visit(directory: string, prefix: string, found: string[]): void {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    const absolute = join(directory, entry.name);
    visitEntry({ entry, relative, absolute, found });
  }
}

function visitEntry(options: {
  entry: import("node:fs").Dirent;
  relative: string;
  absolute: string;
  found: string[];
}): void {
  const { entry, relative, absolute, found } = options;
  if (isExcludedEntry(relative, absolute)) return;
  if (entry.isDirectory()) return visitDirectory(relative, absolute, found);
  if (entry.isFile() && languageForPath(relative)) found.push(relative);
}

function visitDirectory(
  relative: string,
  absolute: string,
  found: string[],
): void {
  if (!isIgnoredDirectory(relative)) visit(absolute, relative, found);
}

function isExcludedEntry(relative: string, absolute: string): boolean {
  return (
    isSensitiveProjectPath(relative) ||
    isClassificationConfigPath(relative) ||
    lstatSync(absolute).isSymbolicLink()
  );
}

function isIgnoredDirectory(path: string): boolean {
  return path
    .split("/")
    .some((part) =>
      /^(node_modules|\.git|\.hg|\.svn|\.venv|venv)$/iu.test(part),
    );
}

export function languageForPath(path: string): string | undefined {
  const extension = path.split(".").at(-1)?.toLowerCase();
  return (
    {
      rs: "rust",
      py: "python",
      pyi: "python",
      cs: "csharp",
      ts: "typescript",
      tsx: "typescript",
      js: "javascript",
      jsx: "javascript",
    } as Record<string, string>
  )[extension ?? ""];
}

export function hasGeneratedHeader(root: ProjectRoot, path: string): boolean {
  try {
    const header = root.protectedRead(path).bytes.slice(0, 2048);
    const generatedHeaderPattern = new RegExp(
      "(?:^|\\n)\\s*(?:\\/\\/|#|\\/\\*)\\s*" +
        "(?:<auto-generated>|auto-generated\\b|generated by\\b)",
      "iu",
    );
    return generatedHeaderPattern.test(header);
  } catch {
    return false;
  }
}
